name = "JEMallocAllocators"
uuid = "a5f0ca54-753b-450d-a6a0-78c3f3017600"
authors = ["Mark Kittisopikul <kittisopikulm@janelia.hhmi.org> and contributors"]
version = "0.1.0"

[deps]
ArrayAllocators = "c9d4266f-a5cb-439d-837c-c97b191379f5"
jemalloc_jll = "454a8cc1-5e0e-5123-92d5-09b094f0e876"

[compat]
ArrayAllocators = "0.3"
jemalloc_jll = "5.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
